/**
 * Main Street: Card Test Framework — explicit per-card definitions.
 *
 * Every card in `src/card-data.csv` must have exactly one definition here.
 * The framework treats a discovered card with no definition as a FAILURE
 * (never a silent skip), so adding a card to the CSV requires adding a
 * definition below (extensibility contract, AC5).
 *
 * The `verifies` text is derived from the card row for readability; the
 * executable body is the shared family runner in `runners.ts`.
 *
 * @module
 */

import type { CardDefinition } from '../CardTestTypes';
import {
  verifyEventCard,
  verifyPlaceableCard,
  verifyStaffCard,
  verifyUpgradeCard,
} from './runners';

/** Explicit definitions for all cards discovered in card-data.csv. */
export const CARD_DEFINITIONS: readonly CardDefinition[] = [
  { cardId: 'biz-bakery', family: 'business', verifies: "Purchase Bakery from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-diner', family: 'business', verifies: "Purchase Diner from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-bookshop', family: 'business', verifies: "Purchase Bookshop from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-hardware', family: 'business', verifies: "Purchase Hardware Store from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-pawnshop', family: 'business', verifies: "Purchase Pawn Shop from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-boutique', family: 'business', verifies: "Purchase Boutique from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-laundromat', family: 'business', verifies: "Purchase Laundromat from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-barbershop', family: 'business', verifies: "Purchase Barbershop from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-arcade', family: 'business', verifies: "Purchase Arcade from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-cinema', family: 'business', verifies: "Purchase Cinema from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-cafe', family: 'business', verifies: "Purchase Cafe from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-food-truck', family: 'business', verifies: "Purchase Food Truck from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-gallery', family: 'business', verifies: "Purchase Art Gallery from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-spa', family: 'business', verifies: "Purchase Day Spa from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-florist', family: 'business', verifies: "Purchase Flower Shop from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-clinic', family: 'business', verifies: "Purchase Clinic from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-private-clinic', family: 'business', verifies: "Purchase Private Clinic from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-pharmacy', family: 'business', verifies: "Purchase Pharmacy from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-juice-bar', family: 'business', verifies: "Purchase Juice Bar from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-yoga-studio', family: 'business', verifies: "Purchase Yoga Studio from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-physio', family: 'business', verifies: "Purchase Physiotherapist from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-tailor', family: 'business', verifies: "Purchase Tailor from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-gym', family: 'business', verifies: "Purchase Gym from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-dentist', family: 'business', verifies: "Purchase Dentist from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-toy-store', family: 'business', verifies: "Purchase Toy Store from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-music-store', family: 'business', verifies: "Purchase Music Store from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-delicatessen', family: 'business', verifies: "Purchase Delicatessen from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-craft-shop', family: 'business', verifies: "Purchase Craft Shop from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-hotel', family: 'business', verifies: "Purchase Grand Hotel from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-teahouse', family: 'business', verifies: "Purchase Teahouse from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'biz-charity-shop', family: 'business', verifies: "Purchase Charity Shop from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'cs-park', family: 'community-space', verifies: "Purchase Park from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'cs-library', family: 'community-space', verifies: "Purchase Library from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'cs-playground', family: 'community-space', verifies: "Purchase Playground from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'cs-community-garden', family: 'community-space', verifies: "Purchase Community Garden from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'cs-fountain', family: 'community-space', verifies: "Purchase Town Fountain from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'cs-health-kiosk', family: 'community-space', verifies: "Purchase Health Kiosk from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'cs-shelter', family: 'community-space', verifies: "Purchase Community Shelter from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'cs-public-art', family: 'community-space', verifies: "Purchase Public Art from the market, assert its cost/income, and advance a turn.", run: verifyPlaceableCard },
  { cardId: 'evt-festival', family: 'event', verifies: "Resolve Local Festival and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-rainy', family: 'event', verifies: "Resolve Rainy Day and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-tax', family: 'event', verifies: "Resolve Tax Audit and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-award', family: 'event', verifies: "Resolve Community Award and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-inspection', family: 'event', verifies: "Resolve Health Inspection and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-grand-opening', family: 'event', verifies: "Resolve Grand Opening Sale and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-wellness-fair', family: 'event', verifies: "Resolve Wellness Fair and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-block-party', family: 'event', verifies: "Resolve Block Party and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-charity-drive', family: 'event', verifies: "Resolve Charity Drive and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-power-outage', family: 'event', verifies: "Resolve Power Outage and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-shoplifting', family: 'event', verifies: "Resolve Shoplifting Spree and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-noise-complaint', family: 'event', verifies: "Resolve Noise Complaint and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-pipe-burst', family: 'event', verifies: "Resolve Pipe Burst and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-food-critic', family: 'event', verifies: "Resolve Food Critic Visit and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-construction', family: 'event', verifies: "Resolve Road Construction and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-viral-review', family: 'event', verifies: "Resolve Viral Review and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-vandalism', family: 'event', verifies: "Resolve Vandalism and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-flu-outbreak', family: 'event', verifies: "Resolve Flu Outbreak and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-recession', family: 'event', verifies: "Resolve Economic Recession and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-harvest-festival', family: 'event', verifies: "Resolve Harvest Festival and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-health-campaign', family: 'event', verifies: "Resolve Health Campaign and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-street-performer', family: 'event', verifies: "Resolve Street Performer and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-bulk-purchase', family: 'event', verifies: "Resolve Bulk Purchase and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-book-fair', family: 'event', verifies: "Resolve Book Fair and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-volunteer-day', family: 'event', verifies: "Resolve Volunteer Day and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-community-garden', family: 'event', verifies: "Resolve Garden Party and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-festival-season', family: 'event', verifies: "Resolve Festival Season and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-protest', family: 'event', verifies: "Resolve Protest and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-supply-chain', family: 'event', verifies: "Resolve Supply Chain Delay and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-power-surge', family: 'event', verifies: "Resolve Power Surge and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-strike', family: 'event', verifies: "Resolve Strike and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-heatwave', family: 'event', verifies: "Resolve Heatwave and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-pest-infestation', family: 'event', verifies: "Resolve Pest Infestation and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-slow-season', family: 'event', verifies: "Resolve Slow Season and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-good-press', family: 'event', verifies: "Resolve Good Press and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-tourist-bus', family: 'event', verifies: "Resolve Tourist Bus and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-cultural-grant', family: 'event', verifies: "Resolve Cultural Grant and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-health-carnival', family: 'event', verifies: "Resolve Health Carnival and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-food-tasting', family: 'event', verifies: "Resolve Food Tasting Tour and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-art-sale', family: 'event', verifies: "Resolve Art Sale and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-shopping-spree', family: 'event', verifies: "Resolve Shopping Spree and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-summer-fest', family: 'event', verifies: "Resolve Summer Fest and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-service-week', family: 'event', verifies: "Resolve Service Week and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-tourist-season', family: 'event', verifies: "Resolve Tourist Season and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-community-renovation', family: 'event', verifies: "Resolve Community Renovation and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-graffiti', family: 'event', verifies: "Resolve Graffiti and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-graffiti-art', family: 'event', verifies: "Resolve Graffiti Art and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-water-main', family: 'event', verifies: "Resolve Water Main Break and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-parking-tickets', family: 'event', verifies: "Resolve Parking Enforcement and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-labor-shortage', family: 'event', verifies: "Resolve Labor Shortage and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-movie-premiere', family: 'event', verifies: "Resolve Movie Premiere and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-health-screening', family: 'event', verifies: "Resolve Free Health Screening and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-farmers-market', family: 'event', verifies: "Resolve Farmers Market Day and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-library-reading', family: 'event', verifies: "Resolve Children\\'s Story Hour and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-street-cleaning', family: 'event', verifies: "Resolve Street Cleaning and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-neighborhood-watch', family: 'event', verifies: "Resolve Neighborhood Watch and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'upg-patisserie', family: 'upgrade', verifies: "Buy Upgrade to Patisserie and assert it upgrades its target business (Bakery).", run: verifyUpgradeCard },
  { cardId: 'upg-bistro', family: 'upgrade', verifies: "Buy Upgrade to Bistro and assert it upgrades its target business (Diner).", run: verifyUpgradeCard },
  { cardId: 'upg-readers-cafe', family: 'upgrade', verifies: "Buy Upgrade to Reader\\'s Café and assert it upgrades its target business (Bookshop).", run: verifyUpgradeCard },
  { cardId: 'upg-garden', family: 'upgrade', verifies: "Buy Upgrade to Garden and assert it upgrades its target business (Park).", run: verifyUpgradeCard },
  { cardId: 'upg-home-improvement', family: 'upgrade', verifies: "Buy Upgrade to Home Improvement and assert it upgrades its target business (Hardware Store).", run: verifyUpgradeCard },
  { cardId: 'upg-vintage-shop', family: 'upgrade', verifies: "Buy Upgrade to Vintage Shop and assert it upgrades its target business (Pawn Shop).", run: verifyUpgradeCard },
  { cardId: 'upg-designer-store', family: 'upgrade', verifies: "Buy Upgrade to Designer Store and assert it upgrades its target business (Boutique).", run: verifyUpgradeCard },
  { cardId: 'upg-dry-cleaners', family: 'upgrade', verifies: "Buy Upgrade to Dry Cleaners and assert it upgrades its target business (Laundromat).", run: verifyUpgradeCard },
  { cardId: 'upg-salon', family: 'upgrade', verifies: "Buy Upgrade to Salon and assert it upgrades its target business (Barbershop).", run: verifyUpgradeCard },
  { cardId: 'upg-gaming-lounge', family: 'upgrade', verifies: "Buy Upgrade to Gaming Lounge and assert it upgrades its target business (Arcade).", run: verifyUpgradeCard },
  { cardId: 'upg-imax', family: 'upgrade', verifies: "Buy Upgrade to IMAX Theater and assert it upgrades its target business (Cinema).", run: verifyUpgradeCard },
  { cardId: 'upg-roastery', family: 'upgrade', verifies: "Buy Upgrade to Roastery and assert it upgrades its target business (Cafe).", run: verifyUpgradeCard },
  { cardId: 'upg-gourmet-truck', family: 'upgrade', verifies: "Buy Upgrade to Gourmet Truck and assert it upgrades its target business (Food Truck).", run: verifyUpgradeCard },
  { cardId: 'upg-museum', family: 'upgrade', verifies: "Buy Upgrade to Museum and assert it upgrades its target business (Art Gallery).", run: verifyUpgradeCard },
  { cardId: 'upg-resort-spa', family: 'upgrade', verifies: "Buy Upgrade to Resort Spa and assert it upgrades its target business (Day Spa).", run: verifyUpgradeCard },
  { cardId: 'upg-garden-center', family: 'upgrade', verifies: "Buy Upgrade to Garden Center and assert it upgrades its target business (Flower Shop).", run: verifyUpgradeCard },
  { cardId: 'upg-medical-center', family: 'upgrade', verifies: "Buy Upgrade to Medical Center and assert it upgrades its target business (Clinic).", run: verifyUpgradeCard },
  { cardId: 'upg-private-medical-center', family: 'upgrade', verifies: "Buy Upgrade to Private Medical Center and assert it upgrades its target business (Private Clinic).", run: verifyUpgradeCard },
  { cardId: 'upg-bread-factory', family: 'upgrade', verifies: "Buy Upgrade to Bread Factory and assert it upgrades its target business (Bakery).", run: verifyUpgradeCard },
  { cardId: 'upg-fast-food', family: 'upgrade', verifies: "Buy Upgrade to Fast Food and assert it upgrades its target business (Diner).", run: verifyUpgradeCard },
  { cardId: 'upg-drive-in', family: 'upgrade', verifies: "Buy Upgrade to Drive-In Theater and assert it upgrades its target business (Cinema).", run: verifyUpgradeCard },
  { cardId: 'upg-wellness-center', family: 'upgrade', verifies: "Buy Upgrade to Wellness Center and assert it upgrades its target business (Day Spa).", run: verifyUpgradeCard },
  { cardId: 'upg-grand-bakehouse', family: 'upgrade', verifies: "Buy Upgrade to Grand Bakehouse and assert it upgrades its target business (Bakery).", run: verifyUpgradeCard },
  { cardId: 'upg-restaurant', family: 'upgrade', verifies: "Buy Upgrade to Restaurant and assert it upgrades its target business (Diner).", run: verifyUpgradeCard },
  { cardId: 'upg-multiplex', family: 'upgrade', verifies: "Buy Upgrade to Multiplex and assert it upgrades its target business (Cinema).", run: verifyUpgradeCard },
  { cardId: 'upg-luxury-retreat', family: 'upgrade', verifies: "Buy Upgrade to Luxury Retreat and assert it upgrades its target business (Day Spa).", run: verifyUpgradeCard },
  { cardId: 'upg-community-hub', family: 'upgrade', verifies: "Buy Upgrade to Community Hub and assert it upgrades its target business (Library).", run: verifyUpgradeCard },
  { cardId: 'upg-smoothie-bar', family: 'upgrade', verifies: "Buy Upgrade to Smoothie Bar and assert it upgrades its target business (Juice Bar).", run: verifyUpgradeCard },
  { cardId: 'upg-wellness-retreat', family: 'upgrade', verifies: "Buy Upgrade to Wellness Retreat and assert it upgrades its target business (Yoga Studio).", run: verifyUpgradeCard },
  { cardId: 'upg-fitness-center', family: 'upgrade', verifies: "Buy Upgrade to Fitness Center and assert it upgrades its target business (Gym).", run: verifyUpgradeCard },
  { cardId: 'upg-dental-clinic', family: 'upgrade', verifies: "Buy Upgrade to Dental Clinic and assert it upgrades its target business (Dentist).", run: verifyUpgradeCard },
  { cardId: 'upg-bespoke-tailor', family: 'upgrade', verifies: "Buy Upgrade to Bespoke Tailor and assert it upgrades its target business (Tailor).", run: verifyUpgradeCard },
  { cardId: 'upg-toy-warehouse', family: 'upgrade', verifies: "Buy Upgrade to Toy Warehouse and assert it upgrades its target business (Toy Store).", run: verifyUpgradeCard },
  { cardId: 'upg-tea-lounge', family: 'upgrade', verifies: "Buy Upgrade to Tea Lounge and assert it upgrades its target business (Teahouse).", run: verifyUpgradeCard },
  { cardId: 'upg-gourmet-deli', family: 'upgrade', verifies: "Buy Upgrade to Gourmet Deli and assert it upgrades its target business (Delicatessen).", run: verifyUpgradeCard },
  { cardId: 'upg-adventure-park', family: 'upgrade', verifies: "Buy Upgrade to Adventure Park and assert it upgrades its target business (Playground).", run: verifyUpgradeCard },
  { cardId: 'upg-orchard', family: 'upgrade', verifies: "Buy Upgrade to Orchard and assert it upgrades its target business (Community Garden).", run: verifyUpgradeCard },
  { cardId: 'upg-grand-fountain', family: 'upgrade', verifies: "Buy Upgrade to Grand Fountain and assert it upgrades its target business (Town Fountain).", run: verifyUpgradeCard },
  { cardId: 'upg-health-center', family: 'upgrade', verifies: "Buy Upgrade to Health Center and assert it upgrades its target business (Health Kiosk).", run: verifyUpgradeCard },
  { cardId: 'staff-assistant', family: 'staff', verifies: "Hire Assistant and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-manager', family: 'staff', verifies: "Hire Manager and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-director', family: 'staff', verifies: "Hire Director and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-apprentice', family: 'staff', verifies: "Hire Apprentice and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-executive', family: 'staff', verifies: "Hire Executive and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-socialite', family: 'staff', verifies: "Hire Socialite and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-accountant', family: 'staff', verifies: "Hire Accountant and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-general-manager', family: 'staff', verifies: "Hire General Manager and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-lookout', family: 'staff', verifies: "Hire Lookout and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-barista', family: 'staff', verifies: "Hire Barista and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-security', family: 'staff', verifies: "Hire Security Guard and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-marketing', family: 'staff', verifies: "Hire Marketing Consultant and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-bookkeeper', family: 'staff', verifies: "Hire Bookkeeper and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-customer-rep', family: 'staff', verifies: "Hire Customer Service Rep and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-it', family: 'staff', verifies: "Hire IT Specialist and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-health-safety', family: 'staff', verifies: "Hire Health & Safety Inspector and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-event-planner', family: 'staff', verifies: "Hire Event Planner and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-delivery', family: 'staff', verifies: "Hire Delivery Driver and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-pr', family: 'staff', verifies: "Hire PR Officer and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-financial', family: 'staff', verifies: "Hire Financial Advisor and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-maintenance', family: 'staff', verifies: "Hire Maintenance Worker and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-investor', family: 'staff', verifies: "Hire Investor and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'evt-tax-error', family: 'event', verifies: "Resolve Error in Tax Return and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-tax-inquiry', family: 'event', verifies: "Resolve Inquiry Commission and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-strike-service', family: 'event', verifies: "Resolve Service Workers Strike and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-general-strike', family: 'event', verifies: "Resolve General Strike and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-popular-menu', family: 'event', verifies: "Resolve Popular Menu Item and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-farm-table', family: 'event', verifies: "Resolve Farm-to-Table Feature and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-depression', family: 'event', verifies: "Resolve Depression and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-pandemic', family: 'event', verifies: "Resolve Pandemic and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'staff-florist', family: 'staff', verifies: "Hire Florist and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-baker', family: 'staff', verifies: "Hire Baker and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-chef', family: 'staff', verifies: "Hire Chef and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'staff-mechanic', family: 'staff', verifies: "Hire Mechanic and assert its declared staff abilities.", run: verifyStaffCard },
  { cardId: 'evt-st-brigids', family: 'event', verifies: "Resolve St Brigid\\'s Day and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-st-patricks', family: 'event', verifies: "Resolve St Patrick\\'s Day and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-easter', family: 'event', verifies: "Resolve Easter and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-may-day', family: 'event', verifies: "Resolve May Day / Bealtaine and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-lughnasadh', family: 'event', verifies: "Resolve Lughnasadh and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-samhain', family: 'event', verifies: "Resolve Samhain / Halloween and assert its declared coin/reputation effect.", run: verifyEventCard },
  { cardId: 'evt-christmas', family: 'event', verifies: "Resolve Christmas and assert its declared coin/reputation effect.", run: verifyEventCard },
];
