/// <reference types="vitest" />
/**
 * Vite config for the tce-main-street single-game launcher.
 *
 * AUTO-GENERATED by scripts/game-repo-scaffold.ts — edit that template rather
 * than this file so a re-scaffold does not clobber local changes.
 *
 * The engine toolchain (the config-driven game-discovery plugin and the core
 * path aliases) is imported from the sibling core checkout at `./core`.
 */
import { defineConfig } from 'vite';
import path from 'path';
import fs from 'fs';
import {
  gameDiscoveryPlugin,
  resolveCoreAliases,
} from './core/scripts/vite-game-discovery-plugin';

const coreRoot = path.resolve(__dirname, './core');
const pkg = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, 'package.json'), 'utf-8'),
);
/**
 * Production base path for the GitHub Pages project site.
 *
 * Derived generically from the package name (the last path segment, so a
 * scoped package like `@scope/game` yields `/game/`), with a `PAGES_BASE`
 * environment override for forks or custom domains. No hard-coded repository
 * name appears outside this derivation, so a re-scaffold (which regenerates
 * this file from `core/scripts/game-repo-scaffold.ts`) never regresses it.
 */
function resolvePagesBase(): string {
  const override = process.env.PAGES_BASE;
  if (override && override.trim() !== '') {
    const trimmed = override.trim();
    return trimmed === '/' ? '/' : `/${trimmed.replace(/^\/+|\/+$/g, '')}/`;
  }
  const name = String(pkg.name ?? 'app');
  const segment = name.includes('/') ? name.slice(name.lastIndexOf('/') + 1) : name;
  return `/${segment}/`;
}
// A game repo's only preset is ./configs/game.json; the
// plugin default (core-only) applies to the core repo. GAMES_CONFIG can
// still override for an ad-hoc build.
const presetEnv = {
  ...process.env,
  GAMES_CONFIG: process.env.GAMES_CONFIG ?? 'game',
};

export default defineConfig(({ mode }) => ({
  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
  },
  // Electron loads the bundle over file://, so relative asset URLs are required.
  // Electron uses file:// → relative paths; production (GitHub Pages)
  // uses the project path derived from the package name; dev uses root
  // (localhost serves at /).
  base: mode === 'electron' ? './' : mode === 'production' ? resolvePagesBase() : '/',
  plugins: [
    // Reads ./configs/game.json and generates
    // 'virtual:game-registry' (Gym from the core + this one game).
    gameDiscoveryPlugin({ projectRoot: __dirname, coreRoot, env: presetEnv }),
  ],
  resolve: {
    alias: resolveCoreAliases(coreRoot),
  },
  build: {
    outDir: 'dist',
    sourcemap: true,
  },
  server: {
    port: 3000,
    open: false,
  },
  test: {
    projects: [
      // A game repo ships only its own unit suite; browser/teacher profiles
      // live in the launcher distribution.
      {
        extends: true,
        test: {
          name: 'unit',
          globals: true,
          environment: 'node',
          // The replay CLI subprocess inherits this: it must resolve the
          // repo's single-game preset to register the game's adapter.
          env: { GAMES_CONFIG: 'game' },
          include: ['tests/**/*.test.ts'],
          exclude: ['tests/**/*.browser.test.ts'],
          testTimeout: 15_000,
          maxWorkers: 4,
        },
      },
    ],
  },
}));
