/**
 * Main Street card art lookup (CG-0MTORJ5FS006B0UN).
 *
 * Maps a card name to the base64 PNG embedded in that card's 64×64 art zone.
 * The art data and alias table are generated by
 * `scripts/generate-main-street-card-art.mjs` from the committed
 * `sprites/<Name>_64_x_64.png` files, so a card face is self-contained (the
 * SVG is rasterised from a `data:` URI, where external image references do
 * not resolve).
 *
 * Resolution order:
 *   1. Explicit spelling alias (e.g. "Labor Shortage" -> "Labour Shortage").
 *   2. Exact card-name match.
 *   3. The generic `Fallback` sprite.
 *
 * @module
 */

import artMapJson from './card-art-map.json';

interface CardArtMap {
  version: number;
  artSize: number;
  fallback: string;
  aliases: Record<string, string>;
  art: Record<string, string>;
}

const MAP = artMapJson as CardArtMap;

/** Side length (px) of the square card-art zone. */
export const CARD_ART_SIZE = MAP.artSize;

/** Sprite base name used when a card has no dedicated art. */
export const CARD_ART_FALLBACK = MAP.fallback;

/**
 * Resolve a card name to the sprite base name used for its art. Falls back to
 * the generic `Fallback` sprite when no dedicated art exists.
 *
 * @param cardName - The card's display/name field.
 * @returns A sprite base name present in `MAP.art` (or the fallback name).
 */
export function resolveCardArtName(cardName: string): string {
  const trimmed = (cardName ?? '').trim();
  const aliased = MAP.aliases[trimmed] ?? trimmed;
  if (MAP.art[aliased]) return aliased;
  return MAP.fallback;
}

/**
 * Whether a card has dedicated (non-fallback) art.
 *
 * @param cardName - The card's name field.
 */
export function hasDedicatedCardArt(cardName: string): boolean {
  const trimmed = (cardName ?? '').trim();
  const aliased = MAP.aliases[trimmed] ?? trimmed;
  return Boolean(MAP.art[aliased]);
}

/**
 * Return the base64 `data:image/png` URI for a card's 64×64 art.
 *
 * @param cardName - The card's name field.
 * @returns A self-contained data URI suitable for an SVG `<image href>`.
 */
export function getCardArtDataUri(cardName: string): string {
  return MAP.art[resolveCardArtName(cardName)];
}

/** Number of sprites that have generated 64×64 art (mostly for diagnostics). */
export function cardArtSpriteCount(): number {
  return Object.keys(MAP.art).length;
}
