/**
 * Main Street card art lookup (CG-0MTORJ5FS006B0UN).
 *
 * Maps a card name to the base64 bitmap embedded in that card's 64×64 art
 * zone. The art data and alias table are generated by
 * `scripts/generate-main-street-card-art.mjs` from the committed
 * `sprites/<Name>_1024_x_1024.png` files, so a card face is self-contained
 * (the SVG is rasterised from a `data:` URI, where external image references
 * do not resolve).
 *
 * CG-0MUCM36EQ008YP4R: the embedded bitmap is 256×256 WebP — the 64×64 zone is
 * a layout dimension in SVG user units, not the render resolution. Phaser
 * rasterises the card SVG at up to 4× quality scale, so a 64×64 bitmap was
 * stretched to 256×256 device pixels and appeared pixelated.
 *
 * Resolution order:
 *   1. Explicit spelling alias (e.g. "Labor Shortage" -> "Labour Shortage").
 *   2. Exact card-name match.
 *   3. The generic `Fallback` sprite.
 *
 * @module
 */

import artMapJson from './card-art-map.json';

interface CardArtMap {
  version: number;
  artSize: number;
  artResolution: number;
  format: string;
  fallback: string;
  aliases: Record<string, string>;
  art: Record<string, string>;
}

const MAP = artMapJson as CardArtMap;

/**
 * Side length (SVG user units) of the square card-art *zone* on every card
 * face. This is a layout dimension, not the embedded bitmap resolution.
 */
export const CARD_ART_SIZE = MAP.artSize;

/**
 * Side length (px) of the embedded art *bitmap* — how much detail the source
 * art carries before the SVG rasteriser downsamples it into the zone.
 */
export const CARD_ART_RESOLUTION = MAP.artResolution;

/** Media type of the embedded art bitmap (`image/webp`). */
export const CARD_ART_FORMAT = MAP.format;

/** Sprite base name used when a card has no dedicated art. */
export const CARD_ART_FALLBACK = MAP.fallback;

/**
 * Resolve a card name to the sprite base name used for its art. Falls back to
 * the generic `Fallback` sprite when no dedicated art exists.
 *
 * @param cardName - The card's display/name field.
 * @returns A sprite base name present in `MAP.art` (or the fallback name).
 */
export function resolveCardArtName(cardName: string): string {
  const trimmed = (cardName ?? '').trim();
  const aliased = MAP.aliases[trimmed] ?? trimmed;
  if (MAP.art[aliased]) return aliased;
  return MAP.fallback;
}

/**
 * Whether a card has dedicated (non-fallback) art.
 *
 * @param cardName - The card's name field.
 */
export function hasDedicatedCardArt(cardName: string): boolean {
  const trimmed = (cardName ?? '').trim();
  const aliased = MAP.aliases[trimmed] ?? trimmed;
  return Boolean(MAP.art[aliased]);
}

/**
 * Return the base64 `data:image/webp` URI for a card's art bitmap.
 *
 * @param cardName - The card's name field.
 * @returns A self-contained data URI suitable for an SVG `<image href>`.
 */
export function getCardArtDataUri(cardName: string): string {
  return MAP.art[resolveCardArtName(cardName)];
}

/** Number of sprites that have generated art (mostly for diagnostics). */
export function cardArtSpriteCount(): number {
  return Object.keys(MAP.art).length;
}
